module.exports = function(grunt) {
    
    grunt.initConfig({
        
        //包文件
        pkg: grunt.file.readJSON('package.json'),
        
        //清除文件
        clean: {
            main: {
                src: 'build/*'
            }
        },
        
        // 拷贝文件
        copy : {
            main: {
                files:[
                    {
                        expand:true,
                        src: ['**/*.js'],
                        dest: 'build/', 
                        cwd:'src/'
                    }
                ]
            }
        },

        // 压缩js
        uglify: {
            options: {
                banner: '/*! Generated by Grunt: <%= pkg.github %> <%= grunt.template.today("yyyy-mm-dd hh:MM:ss") %> */\n',
                beautify: {
                    ascii_only: true
                }
            },
            main: {
                files: [
                    {
                        expand: true,
                        cwd: 'build/',
                        src: ['**/*.js', '!**/*-min.js'],
                        dest: 'build/',
                        ext: '-min.js'
                    }
                ]
            }
        }
        
    });
    
    //加载任务
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    
    //注册默认任务
    grunt.registerTask('default', ['clean', 'copy', 'uglify']);

};